### ISSUE TITLE
Image not accepted with image grader toggled off

### ISSUE THREAD

**Issue by sven-hoffmann** [tcpalmer/nina.plugin.assistant#80]
Hi Tom,

I became aware of your project through the Astro Imaging Channel video. Thank you for your work! I really like what you've done here and I actively use it with my setup now. 

I ran into a small issue. I am using NINA 2, so v0.8.0 of your plugin. I had troubles with the image grader in that version being too aggressive and I couldn't find configuration options so I switched it off. I noticed that images were no longer being accepted. I suspect this is because the default in [this piece of code](https://github.com/tcpalmer/nina.plugin.assistant/blob/647c2cf1b8680654e0379a4a4190c742a9a3706c/NINA.Plugin.Assistant/NINA.Plugin.Assistant/Sequencer/ImageSaveWatcher.cs#L85) is set to false instead of true. So projects / targets / exposure plans no longer progress or finish because the computation I saw in different places seems to be "TODO = Desired - Accepted".

Just reading the code of the new version it seems this may also still be there.

**Comment by tcpalmer** [comment]
Glad you're finding it useful!

The code is correct: if grading is disabled, images are effectively rejected and the Accepted count on the associated Exposure Plan is not incremented.  The intent is that you will increment Accepted manually on your exposure plans once you've graded them yourself (outside NINA).

But if grading is too aggressive for you, you can adjust the settings.  If you select your Profile name in the left nav, the right panel will show info on the profile.  Click the gear icon to get to the TS preferences for the profile.

But if you still want to leave grading off, you have another option: Exposure Throttle.  The planner will stop scheduling exposures for a plan when the total number taken (Acquired) exceeds some threshold.

See the docs for profile preferences: https://tcpalmer.github.io/nina-scheduler/target-management/profiles.html.  The docs are for the NINA 3 version now but I don't think anything on this page has changed.

**Comment by sven-hoffmann** [comment]
Hi again. Thanks for the fast response and showing me the additional options. It didn't occur to me to look into the profile configuration. I think this solves my issue :) I suppose it was a case of RTFM after all :sweat_smile:
